apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: pyui
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
