name: CD
on:
  workflow_dispatch:
    inputs:
      EC2_IP:
        description: "The IP address of the Kind EC2 instance"
        required: true

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Repo to Kind EC2
        run: |
          # Save the SSH private key to a file
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 400 key.pem

          # Use rsync to copy the repository, excluding key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" --exclude 'key.pem' ./ ec2-user@${{ inputs.EC2_IP }}:~/repo

      - name: Deploy to kind Cluster
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ inputs.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/repo/k8s-manifests

            # TODO: deploy k8s yaml
